program: train.py
method: bayes
metric:
  name: eval/accuracy
  goal: maximize
parameters:
  # training.warmup_ratio: 0.1
  training.learning_rate:
    min: 0.00001
    max: 0.0001
  training.gradient_accumulation_steps:
    min: 1
    max: 32
  training.per_device_train_batch_size:
    values: [8,16,32]
  training.weight_decay: 
    min: 0.001
    max: 0.1
  # training.load_best_model_at_end: False


early_terminate:
  type: hyperband
  min_iter: 3

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
  - ~training.run_name