program: train.py
method: bayes
metric:
  name: best_eval/accuracy
  goal: maximize
parameters:
  # training.warmup_ratio: 0.1
  training.learning_rate:
    min: 0.0000005
    max: 0.0005
  training.gradient_accumulation_steps:
    min: 1
    max: 32
  training.weight_decay: 
    min: 0.001
    max: 0.1
  training.num_train_epochs: 
    min: 1
    max: 5
  model.checkpoint:
    values: ["bert-base-cased","bert-base-uncased", "roberta-base"]
  # training.load_best_model_at_end: False


early_terminate:
  type: hyperband
  min_iter: 3

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args_no_hyphens}
  # - ~training.run_name